### ISSUE TITLE
Support for davical ?

### ISSUE THREAD

**Issue by section1** [scopen-coop/roundcube_caldav#10]
Hi, im testing this in roundcube and davical caldav server.. when i accept an invitation i get an 412 error: 

For example if accept this invitation via thunderbird and the go back to roundcube and accept again with this plugin i don't get any error.

i think is something related with this line : 

LOG: request:-->ATTENDEE;RSVP=TRUE;CN=USERB;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUA

should be maybe:  PARTSTAT=ACCEPTED ?

what can be the problem?
thanks.

LOGS: 

 LOG: :***************** Request Header ****************
 LOG: :PUT /caldav.php/USER/calendar/ea5aa3f3-8daa-4e4e-8507-ba7ec2d564e8.ics
 LOG: headers:-->Host: calendar.domain2.tld
 LOG: headers:-->Authorization: Delicious tasty password eaten by debugging monster!
 LOG: headers:-->Accept: */*
 LOG: headers:-->Depth: 1
 LOG: headers:-->Content-Type: text/calendar; charset='UTF-8'
 LOG: headers:-->Content-Length: 843
 LOG: :******************** Request ********************
 LOG: request:-->BEGIN:VCALENDAR
 LOG: request:-->PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
 LOG: request:-->VERSION:2.0
 LOG: request:-->BEGIN:VTIMEZONE
 LOG: request:-->TZID:America/REMOVED
 LOG: request:-->BEGIN:STANDARD
 LOG: request:-->TZOFFSETFROM:-0300
 LOG: request:-->TZOFFSETTO:-0300
 LOG: request:-->TZNAME:-03
 LOG: request:-->DTSTART:19700101T000000
 LOG: request:-->END:STANDARD
 LOG: request:-->END:VTIMEZONE
 LOG: request:-->BEGIN:VEVENT
 LOG: request:-->CREATED:20230309T151405Z
 LOG: request:-->LAST-MODIFIED:20230309T161741Z
 LOG: request:-->DTSTAMP:20230309T151406Z
 LOG: request:-->UID:ea5aa3f3-8daa-4e4e-8507-ba7ec2d564e8
 LOG: request:-->SUMMARY:Test 3
 LOG: request:-->STATUS:CONFIRMED
 LOG: request:-->ORGANIZER;CN=USERA@domain.tld:mailto:USERA@domain.tld
 LOG: request:-->ATTENDEE;RSVP=TRUE;CN=USERB;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUA
 LOG: request:--> L;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:USERB@domain2.tld
 LOG: request:-->DTSTART;TZID=America/REMOVED:20230313T130000
 LOG: request:-->DTEND;TZID=America/REMOVED:20230313T140000
 LOG: request:-->SEQUENCE:1
 LOG: request:-->TRANSP:OPAQUE
 LOG: request:-->END:VEVENT
 LOG: request:-->END:VCALENDAR
 LOG: request:-->
 LOG: :Response status 412 for PUT /caldav.php/USERB/calendar/ea5aa3f3-8daa-4e4e-8507-ba7ec2d564e8.ics
 LOG: :***************** Response Header ****************
 LOG: headers:-->Server: 1.1
 LOG: headers:-->DAV: 1, 2, 3, access-control, calendar-access, calendar-schedule
 LOG: headers:-->DAV: extended-mkcol, bind, addressbook, calendar-proxy
 LOG: headers:-->X-DAViCal-Version: DAViCal/1.1.9; DB/1.3.3
 LOG: headers:-->Content-type: text/plain; charset="utf-8"
 LOG: :******************** Response ********************
 LOG: response:-->No calendar content

**Comment by noec764** [comment]
Hi @section1, 
Can you send me the original ics file before roundcube_caldav 's modification ?
And if it is possible the ics file generated by Thunderbird to compare ?  

For the line: 
```
ATTENDEE;RSVP=TRUE;CN=USERB;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:USERB@domain2.tld
```
If the user who validates this invitation is the organiser, this is the normal procedure. But your error message in your Davical server is `No calendar content` , so I don't think that's where the problem is.

Maybe it is a parse error due to line break.

**Comment by section1** [comment]
Hi @noec764  ! thanks for your reply and time ! i make a new test today and i attach with the data you asked.

1-  first i save the  ICS file(ainvite.ics.log)
2- I confirm the invitation via roundcube using the plugin and fails(plugin-davical.log)
3- I accept the same invitation via thunderbird and works(thunderb-davical.log)

If you need more info don't hesitate to ask.

[invite.ics.log](https://github.com/scopen-coop/roundcube_caldav/files/10958797/invite.ics.log)
[plugin-davical.log](https://github.com/scopen-coop/roundcube_caldav/files/10958801/plugin-davical.log)
[thunderb-davical.log](https://github.com/scopen-coop/roundcube_caldav/files/10958807/thunderb-davical.log)

**Comment by FHenry** [comment]
Issue close cause of more than year inactivites
