### ISSUE TITLE
Events are not displayed in calendar

### ISSUE THREAD

**Issue by Kulturserver** [scopen-coop/roundcube_caldav#11]
We've installed and activated the plugin for roundcube version 1.5.1
We are able to use kopano as a caldav server and added an url: http://kopano.domain.tld:8080/caldav/public/calendarname
Username and password are saved successfully - so it says.

But when we open the calendar itself, no events are shown, although there are plenty - the url works in a browser as well as in thunderbird, but it appears to be empty in roundcube.

Any help would be highly appreciated, thanks!

**Comment by noec764** [comment]
I'm not sure I understand your problem.
This plugin does not import events into roundcube, it does the opposite, it can export events received by email into your caldav server.

**Comment by Kulturserver** [comment]
Oh, we were on the totally wrong track then - thanks for your reply and sorry!
