### ISSUE TITLE
Question: does this also work with Google Agenda

### ISSUE THREAD

**Issue by Jordo-o** [scopen-coop/roundcube_caldav#13]
I was trying to integrate this with the google calendar (CalDAV API).
But I couldn't get it working. Maybe someone who has tried this already?

**Comment by FHenry** [comment]
Unfortunately as Google do not support calDav protocol as client anymore (at least since 2021 https://support.google.com/calendar/thread/97494333/syncing-caldav-calendar-to-google-from-caldav-to-google?hl=en) we are not able to follow this request. This issue is closed
