### ISSUE TITLE
Distribution-packaging friendly release packages?

### ISSUE THREAD

**Issue by netchild** [scopen-coop/roundcube_caldav#16]
Would it be possible for you to create 3rd party package management friendly releases?

Running composer during a package-build is a no-go in certain package building systems. For the one package management system I want to integrate your plugin into, there are fetch, extract and build stages (ans some more). During the fetch stage all the software is downloaded, and during the build stage any commands can be executed (e.g. to compile C code or something like that), but no network access is possible outside the fetch stage.

Running composer is not feasible in the fetch stage, as your code is not yet downloaded. And running it in the post-extract or build stage is not possible due to no network access. Having all the dependencies composer would download inside your release-tarball would fix this problem.

**Comment by FHenry** [comment]
Hi, this RoundCube module is dedicated to users/admins who are able to use composer command line as it is describe in README.md. 
We cannot afford to include in to package the composer component. 
It's deliver "as is", but if you want to make it "auto-deploy-able" and find a way to promote this module to RoundCube core we will be happy to participate
