### ISSUE TITLE
Use webmail username/password as option

### ISSUE THREAD

**Issue by tomsommer** [scopen-coop/roundcube_caldav#17]
Would be nice if it was not needed to maintain username and password for the caldav separately, if the username and password is the same as a login to the webmail.

So an option to have "use same credentials as roundcube" would be awesome

**Comment by FHenry** [comment]
hello @tomsommer 

The fact is RoundCube do not store user password in "clear" anywhere.
And in our use case, our user credential on mail stack is not linked with our Caldav Provider.

But if someone in tech team at Simply.com want to send a PR we will be happy to study it.

Have a nice day
