### ISSUE TITLE
Failing when trying to configure CalDav

### ISSUE THREAD

**Issue by hinermat** [scopen-coop/roundcube_caldav#4]
I followed the instructions for installing the plugin.  Everything seemed to go Ok.  When I try to configure my NextCloud server I get an error.  My Settings screen only has 3 fields (server URL, username & password) where your screenshots seems to indicate there should be more.  

Please see attachments for details.
![Screenshot 2022-06-07 at 16-18-19 Roundcube Webmail Preferences](https://user-images.githubusercontent.com/107077226/172475503-67a69836-eff5-49e0-abd2-f0ed1b9249d0.png)
![Screenshot 2022-06-07 at 16-20-23 Roundcube Webmail Preferences](https://user-images.githubusercontent.com/107077226/172475517-b1dca38f-998b-44d4-b54f-a232397a9132.png)

**Comment by noec764** [comment]
Can you show me the roundcube log file where the error is generated ? 
It is located in $yourRoundcubeRoot/logs/errors.log

**Comment by noec764** [comment]
Can you make a ```git pull``` in the plugin root ? (  $yourRoundcubeRoot/plugins/roundcube_caldav)

**Comment by hinermat** [comment]
I did the get pull again and it's still doing the same thing.  Here is the output:

[root@mail plugins]# git clone https://github.com/scopen-coop/roundcube_caldav.git 
Cloning into 'roundcube_caldav'...
remote: Enumerating objects: 818, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 818 (delta 67), reused 86 (delta 35), pack-reused 687
Receiving objects: 100% (818/818), 443.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (473/473), done.

I also re-ran the composer update just to be on the safe side

[root@mail roundcube_caldav]# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing thecsea/simple-caldav-client (v0.1.14): Loading from cache
  - Installing doctrine/collections (1.6.8): Loading from cache
  - Installing simshaun/recurr (v5.0.0): Loading from cache
  - Installing johngrogg/ics-parser (v3.1.1): Loading from cache
  - Installing fortawesome/font-awesome (5.15.4): Loading from cache
Writing lock file
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

**Comment by noec764** [comment]
The fact that you have only three fields is perfectly normal if your connection failed. But I can't figure out why you don't get a more detailed message on what is happening. Did you try to reenter your caldav server information details ? I wonder if the message still the same as yesterday. You can pull the repo again.

**Comment by hinermat** [comment]
I pull the code again and the same thing is still happening.  The error keeps saying "you have to select one default calendar."  Is there anything I need to do on the calendar side of things?  I have the kolab calendar plugin installed.

**Comment by noec764** [comment]
Thank you for your feedback, it is very helpful!

**Comment by hinermat** [comment]
I did the git pull again and composer update.  I entered my nextcloud information and this time I got the rest of the screen where I can select calendars and a default calendar!

But, now another question:  Unless I'm mistaken, shouldn't I see my nextcloud calendars in roundcube now and all the events within those calendars?  Right now I see nothing.

**Comment by noec764** [comment]
No, there is no calendar view in this plugin. You can only interact with events that you receive via email.
