### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by IgorA100** [scopen-coop/roundcube_caldav#5]
I'm trying to connect with NextCloud
1. Thinks for a very long time when going to the settings.
2. After trying to save the settings, he also thinks for a very long time.
3. It seems to save the URL, login and password, and even gives out a list of calendars, but after turning them on, it also thinks for a very long time and nothing happens.
It may then report that the connection failed.
There are no problems with the NextCloud server, because CardDAV works without problems.

**Comment by IgorA100** [comment]
I looked for a long time and noticed that a login error message is displayed.
Although at some point the login is successful, but very, very rarely
![calDAV](https://user-images.githubusercontent.com/5006170/176789352-98954d2e-136e-472a-baaa-a64b094c0d5d.png)

**Comment by IgorA100** [comment]
My problem is related to SimpleCalDAVClient
I can't connect to the CalDAV server
I am using CURL 7.29.0 and PHP 7.2.30
When using SimpleCalDAVClient alone for ttests, I get a PHP error in log file:

`[01-Jul-2022 14:50:35 Europe/Moscow] PHP Warning:  DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity, line: 1 in /home/...../caldav/simpleCalDAV/CalDAVException.php on line 60
[01-Jul-2022 14:50:35 Europe/Moscow] PHP Fatal error:  Uncaught <pre>Exception: Login failed<br><br><br><br>If you think there is a bug in SimpleCalDAV, please report the following information on github or send it at palm.michael@gmx.de.<br><br><br><br>For debugging purposes:<br><br>last request:<br><br>OPTIONS /remote.php/dav/calendars/igora100/ HTTP/1.1
Authorization: Basic SWdvckExMDA6RnJvZzc2KkZyb2c3Ng==
User-Agent: cURL based CalDAV client
Host: myhost.ex - This is the real host!!!
Accept: */*
Content-type: text/plain

<br>last response:<br><br>HTTP/1.1 401 Unauthorized
Server: nginx
Date: Fri, 01 Jul 2022 11:49:29 GMT
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/8.0.19
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=3mJCHd6gU1AwNopbDh%2FVVM0ziV%2FpApoVVM0ziV%loAhXezwsgQUtEmxucXUN7vsmWrrO%2BOMAnyb8eFYkygokipR1kZUmD8EHvgHo9aitTS7hTDU8PIbe90iafYp0y; path=/; HttpOnly; SameSite=Lax
Set-Cookie: ocrm8tkhp2 in /home/...../caldav/simpleCalDAV/SimpleCalDAVClient.php on line 94
`

**Comment by noec764** [comment]
Thank you for your feedback, 
If you think the problem comes from the SimpleCalDAV Client the easiest way is to create an issue on their GitHub depo https://github.com/thecsea/simpleCalDAV, I am not able to modify their code.
