### ISSUE TITLE
CalDAV sync?

### ISSUE THREAD

**Issue by IgorA100** [scopen-coop/roundcube_caldav#6]
Do you have plans to implement CalDAV synchronization (Calendars, tasks)?

**Comment by noec764** [comment]
You are allowed to make PR for this feature

**Comment by IgorA100** [comment]
I didn't quite understand you :(

**Comment by noec764** [comment]
I don't have time to look into it, but if you want to see this feature in this module, you can develop it ! ;)

**Comment by TCB13** [comment]
Yeah this would be nice, but it is an hard one to develop.
