### ISSUE TITLE
No settings page

### ISSUE THREAD

**Issue by HansHM** [scopen-coop/roundcube_caldav#8]
Hello and goodmoning FHenry,

I have installed your plugin by instruction INSTALL.md, first section.

There is only no settings page in de Setting section of Roundcube. The error log is show no errors, there is no browser errors.
Running Plesk Obsidian, with a viruall Hosting running, Roundcube 1.6, Ubuntu 20.04. PHP 7.3.4, Skins Larry and Elastic.

Under about (RC) roundcube_caldav |   | GPL-3.0+ | Download

I have logged in andout and in to see if thats helps.

**Comment by noec764** [comment]
Hello, 
Did you run the ```composer update``` ?

**Comment by HansHM** [comment]
Yes i did

**Comment by noec764** [comment]
Ok, and did you change the config file ? 
```
Enable RoundCube CalDAV in Roundcube: Open the file config/config.inc.php and add roundcube_caldav to the array $config['plugins'].
```

**Comment by Grinch** [comment]
I have this same issue. The plugin is enabled in the `config.inc.php` file and `composer update` was ran. Just doesn't appear in the settings.

RC 1.6
PHP 8.1.2

**Comment by calidancer** [comment]
Hi,

I have the same issue. My environment is the following:

- RoundCube v1.6 
- From **/etc/roundcube/config.inc.php**:  $config['plugins'] = array('password', 'newmail_notifier', 'zipdownload', 'archive', 'managesieve', 'calendar', 'libcalendaring', 'libkolab', 'carddav');
- PHP: 8.0 however my server can have multiple PHP versions from 5.6 to 8.1 (I'm using HestiaCP)
- According to [this](https://github.com/scopen-coop/roundcube_caldav/blob/bf6dd000c3492338ea882da45a33f1268ce19573/doc/SUPPORTED_ENVIRONMENT.md) I understand that this plugin does not support Round Cube v1.6 however I hope you spare some time to test it

Attached a screenshot of my RoundCube settings view:
![2022-12-16_002254](https://user-images.githubusercontent.com/113770442/207994147-93c6a902-4fba-4eb7-a0ca-a66786f57146.png)

Thanks.

**Comment by noec764** [comment]
>     * From **/etc/roundcube/config.inc.php**:  $config['plugins'] = array('password', 'newmail_notifier', 'zipdownload', 'archive', 'managesieve', 'calendar', 'libcalendaring', 'libkolab', 'carddav');

The plugin is not declared add ```'roundcube_caldav'``` to this array

**Comment by calidancer** [comment]
Hi @noec764 , sorry the content I posted of **$config['plugins']** from **/etc/roundcube/config.inc.php** was 'before' enabling it. 

Thanks for replying though.

**Comment by noec764** [comment]
I think your error is due to the non compatibility of the plugin with roundcube 1.6 as you said.  I will try to check what is wrong but I can't give you a date as I have a lot of other stuffs to do.  So if you want to try to check what is wrong, I'm waiting for your PR !
Thanks for your feedback

**Comment by calidancer** [comment]
Hi @noec764,

I would be glad if you could check it. Sorry but I'm not aware of any other meaning other than "Public Relation" for the abbreviation **PR** :)

BTW I have two environments: Production and Staging. If you want to schedule a quick call whenever suits you, that would be great. I am willing to pay.

**Comment by FHenry** [comment]
@calidancer , could you please take contact with contact@scopen.fr in order to send you a quotation ?

**Comment by Norbert-D** [comment]
Hello 
I am facing the same issue
on both installations

RC 1.6 PHP 7.4
RC 1.5.3 PHP 8

composer update was successful
 plugin is not declared add 'roundcube_caldav'
 
No errors in the log but it does not show up under settings.
I can donate time from a developer on my team if this helps, he would need some help and input how to start and where to look.

**Comment by FHenry** [comment]
@Norbert-D 
Hello, When you says "plugin is not declared add 'roundcube_caldav'" what do you mean ? 

Did you you check into your roundcube roundcube/config.inc.php that the plugin is correctly declared ?

`$config['plugins'] = array(....., 'roundcube_caldav',....);`

**Comment by Norbert-D** [comment]
Yes 

$config['plugins'] =  array(
     'acl',
     'additional_message_headers',
     'archive',
     'attachment_reminder',
     'autologon',
     'filesystem_attachments',
     'hide_blockquote',
     'http_authentication',
     'identicon',
     'identity_select',
     'jqueryui',
      'emoticons',
     'new_user_dialog',
     'new_user_identity',
     'newmail_notifier',
     'managesieve',
     'markasjunk',
     'roundcube_caldav',
     'show_additional_headers',
     'subscriptions_option',
     'userinfo',
     'vcard_attachments',
     'zipdownload',
);

**Comment by Norbert-D** [comment]
![image](https://user-images.githubusercontent.com/63411134/209149623-c35af59f-de74-4298-92cc-5e382395afb0.png)

**Comment by Norbert-D** [comment]
I am not sure if it could be connected to simple-caldav-client 

`use it\thecsea\simple_caldav_client\CalDAVCalendar;
use it\thecsea\simple_caldav_client\CalDAVException;
use it\thecsea\simple_caldav_client\SimpleCalDAVClient;`

the composer was installing it under    roundcube_caldav/vendor/thecsea/simple-caldav-client

**Comment by noec764** [comment]
I think i resolve this issue can you tell me if it is ok for all of you ?

**Comment by Norbert-D** [comment]
Worked for me thanks,
Settings page is there and got connection as it shows the calendar list. 
Will start testing the coming days.
Happy new Year
Thanks Norbert

**Comment by calidancer** [comment]
Hi @noec764 ,
Thanks a lot for having fixed it. I managed to install it in a new fresh environment (just as a test) and in the **RC > Preferences > Configuration of CalDAV** section now I can see all the calendars from my CalDAV server (which is my instance of Nextcloud).

I also installed the following plugins in RC:
- Kolab/calendar
- Kolab/libcalendaring
- Kolab/libkolab

However from the **RC > Calendar** section I can only see my local RC calendar. If I create an event, nothing appears in the calendar on my Nextcloud instance. If I create an event in the calendar of my Nextcloud instance nothing appears in the calendar of my RC.
![image](https://user-images.githubusercontent.com/113770442/209973574-56434769-2c1e-40de-8fab-d7395609df45.png)
![image](https://user-images.githubusercontent.com/113770442/209973720-b8adc4fc-e7bb-4227-9034-332396bb9724.png)
![image](https://user-images.githubusercontent.com/113770442/209973855-276f12e6-7681-4006-971d-47be55a3b773.png)

This is the value of the **$config['plugins']** array in my **config.inc.php** file:
`// List of active plugins (in plugins/ directory)
$config['plugins'] = array('password', 'newmail_notifier', 'zipdownload', 'archive', 'managesieve', 'managesieve', 'roundcube_caldav', 'calendar', 'libcalendaring', 'libkolab');`

This is the content of the RC plugins folder:
![image](https://user-images.githubusercontent.com/113770442/209974148-f3a05282-cf89-4d26-81db-2ac577220536.png)

I'm not sure. Perhaps I'm missing something?

**Comment by FHenry** [comment]
The roundcube Calendar ? I think there is a misunderstanding about the module feature.
There is the use case :
Two Users :Bobby and John
Your roundcube_caldav setting is done to match with Bobby Nexcloud Calendar
With John on Nextcloud  create an event and invite Bobby
with Bobby on roundcube  accept the invitation with the module feature
with Bobby on Nextcloud you should see you event in your calendar.

What you explain is that you want you'r nextcloud calendar into roudcube ? That not the purpose of this module

**Comment by calidancer** [comment]
Hi @FHenry ,
Thanks for the clarification.

@noec764 thanks for your plugin anyway. It's very useful. 

Happy New Year!
